update workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,16 +19,20 @@ jobs:
         with:
           file: pack.zip
           target: pack.zip
-      - name: Rename pack file
-        run: mv pack.zip pack-${{ github.run_number }}.zip
-      - name: Upload to OSS
-        uses: YangHanlin/oss-deployment-action@v1
-        with:
-          oss-endpoint: ${{ secrets.OSS_ENDPOINT }}
-          oss-accesskey-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
-          oss-accesskey-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
-          oss-path: oss://mimaru/assets/
-          local-path: pack-${{ github.run_number }}.zip
+      - name: Install ossutil
+        run: |
+          curl -O http://gosspublic.alicdn.com/ossutil/1.7.19/ossutil64
+          chmod 755 ossutil64
+          mv ossutil64 /usr/local/bin/ossutil
+  
+      - name: Config ossutil
+        run: |
+          ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
+  
+      - name: Upload files to OSS with timeout and error handling
+        run: |
+          set -e
+          timeout 300s ossutil cp -r pack.zip oss://mimaru/assets/ --update || (echo "Upload timed out or failed" && exit 1)
         
         
         
